## Config file

# Log 
seed: 777
use_cuda: 1           # 1 for True, 0 for False

# dataset
speaker_no: 2
mix_lst_path: ./data/LRS2/mixture_data_list_2mix.csv
audio_direc: /mnt/nas_sg/wulanchabu/zexu.pan/datasets/LRS2/audio_clean/
reference_direc: /mnt/nas_sg/wulanchabu/zexu.pan/datasets/LRS2/mvlrs_v1/
audio_sr: 16000
ref_sr: 25

# dataloader
num_workers: 4
batch_size: 4         # 4-GPU training with a total effective batch size of 16
accu_grad: 0
effec_batch_size: 4   # per GPU, only used if accu_grad is set to 1, must be multiple times of batch size
max_length: 6         # truncate the utterances in dataloader, in seconds 

# network settings
init_from: None       # 'None' or a log name 'log_2024-07-22(18:12:13)'
causal: 0             # 1 for True, 0 for False
network_reference:
  cue: lip            # lip or speech or gesture or EEG
  backbone: resnet18  # resnet18 or shufflenetV2 or blazenet64
  emb_size: 256       # resnet18:256
network_audio:
  backbone: av_dprnn
  N: 256
  L: 40
  B: 64
  H: 128
  K: 100
  R: 6

# optimizer
loss_type: sisdr      # "snr", "sisdr", "hybrid"
init_learning_rate: 0.001
max_epoch: 150
clip_grad_norm: 5
[2024-11-22 11:52:31,127] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-11-22 11:52:31,155] torch.distributed.run: [WARNING] 
[2024-11-22 11:52:31,155] torch.distributed.run: [WARNING] *****************************************
[2024-11-22 11:52:31,155] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-11-22 11:52:31,155] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/Users/zhaoshengkui/Downloads/github/ClearerVoice-Studio/train/target_speaker_extraction/train.py", line 1, in <module>
    import yamlargparse, os, random
ModuleNotFoundError: No module named 'yamlargparse'
Traceback (most recent call last):
  File "/Users/zhaoshengkui/Downloads/github/ClearerVoice-Studio/train/target_speaker_extraction/train.py", line 1, in <module>
    import yamlargparse, os, random
ModuleNotFoundError: No module named 'yamlargparse'
[2024-11-22 11:52:36,186] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 31884) of binary: /Users/zhaoshengkui/miniconda3/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/zhaoshengkui/miniconda3/lib/python3.12/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/Users/zhaoshengkui/miniconda3/lib/python3.12/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/Users/zhaoshengkui/miniconda3/lib/python3.12/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/Users/zhaoshengkui/miniconda3/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/Users/zhaoshengkui/miniconda3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoshengkui/miniconda3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-22_11:52:36
  host      : ALI-151052N1.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 31886)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-22_11:52:36
  host      : ALI-151052N1.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 31884)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
